# -- Mouse --
WHEEL_UP    add volume 5
WHEEL_DOWN  add volume -5
#WHEEL_LEFT add volume 0 # Touchpad, am not schizo - Redundant due to disabling default binds
#WHEEL_RIGHT add volume 0

# -- Keyboard --
# Basic playback
k cycle pause
SPACE cycle pause

CTRL+w quit

ESC set fullscreen no
f cycle fullscreen

s screenshot
S screenshot video

# Seek
RIGHT seek 5; script-message prev-page
LEFT seek -5; script-message next-page

l seek 10
j seek -10

SHIFT+RIGHT seek 90
SHIFT+LEFT  seek -90

CTRL+RIGHT add chapter 1; script-message skip-backward
CTRL+LEFT add chapter -1; script-message skip-forward

. frame-step
, frame-back-step

# Volume
UP add volume 5
DOWN add volume -5

# Playback Speed
< add speed -0.25
> add speed 0.25

# Subtites
c cycle sub
= add sub-scale +0.05
- add sub-scale -0.05

# Zoom Pan
CTRL+= add video-zoom 0.05
CTRL+- add video-zoom -0.05

ALT+UP add video-pan-y 0.05
ALT+DOWN add video-pan-y -0.05
ALT+LEFT add video-pan-x 0.05
ALT+RIGHT add video-pan-x -0.05

# Miscellaneous
/ script-message jump-page-mode
i script-binding stats/display-stats
